language: objective-c
osx_image: xcode7.3
script: >
  set -o pipefail &&
  xcodebuild test -workspace App.xcworkspace -scheme App -sdk iphonesimulator9.3
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=9.3'
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4'
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=8.4'
  | xcpretty
